spring:
  #  데이터베이스 커넥션과 관련된 데이터 소스 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # 이러한 설정은 스프링 부트 메뉴얼에 나와있음
  jpa:
    hibernate:
      ddl-auto: create  # create : 애플리케이션 실행 시점에 테이블 생성 (테이블 drop 하고, 다시 생성) -> none : 한 번 데이터 넣어두면 그 데이터 계속 쓸 수 있음
    properties:
      hibernate:
#        show_sql: true # System.out에 출력
        format_sql: true

# 모든 로그 출력은 가급적 로그를 통해 남겨야 한다.
logging:
  level:
    org.hibernate.SQL: debug # Loger를 통해 출력
    org.hibernate.type: trace